#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikasi_peminjaman_barang
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="peminjaman4")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbarang(barang instance);
    partial void Updatebarang(barang instance);
    partial void Deletebarang(barang instance);
    partial void Insertdetailpeminjaman(detailpeminjaman instance);
    partial void Updatedetailpeminjaman(detailpeminjaman instance);
    partial void Deletedetailpeminjaman(detailpeminjaman instance);
    partial void Insertpengguna(pengguna instance);
    partial void Updatepengguna(pengguna instance);
    partial void Deletepengguna(pengguna instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Aplikasi_peminjaman_barang.Properties.Settings.Default.peminjaman4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<barang> barangs
		{
			get
			{
				return this.GetTable<barang>();
			}
		}
		
		public System.Data.Linq.Table<detailpeminjaman> detailpeminjamans
		{
			get
			{
				return this.GetTable<detailpeminjaman>();
			}
		}
		
		public System.Data.Linq.Table<pengguna> penggunas
		{
			get
			{
				return this.GetTable<pengguna>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.barang")]
	public partial class barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_barang;
		
		private string _nama_barang;
		
		private string _status;
		
		private EntitySet<detailpeminjaman> _detailpeminjamans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_barangChanging(string value);
    partial void Onid_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public barang()
		{
			this._detailpeminjamans = new EntitySet<detailpeminjaman>(new Action<detailpeminjaman>(this.attach_detailpeminjamans), new Action<detailpeminjaman>(this.detach_detailpeminjamans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					this.Onid_barangChanging(value);
					this.SendPropertyChanging();
					this._id_barang = value;
					this.SendPropertyChanged("id_barang");
					this.Onid_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(100)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_detailpeminjaman", Storage="_detailpeminjamans", ThisKey="id_barang", OtherKey="id_barang")]
		public EntitySet<detailpeminjaman> detailpeminjamans
		{
			get
			{
				return this._detailpeminjamans;
			}
			set
			{
				this._detailpeminjamans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailpeminjamans(detailpeminjaman entity)
		{
			this.SendPropertyChanging();
			entity.barang = this;
		}
		
		private void detach_detailpeminjamans(detailpeminjaman entity)
		{
			this.SendPropertyChanging();
			entity.barang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailpeminjaman")]
	public partial class detailpeminjaman : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_peminjaman;
		
		private string _id_barang;
		
		private string _id_pengguna;
		
		private string _waktu_peminjaman;
		
		private string _waktu_pemulangan;
		
		private EntityRef<barang> _barang;
		
		private EntityRef<pengguna> _pengguna;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_peminjamanChanging(string value);
    partial void Onid_peminjamanChanged();
    partial void Onid_barangChanging(string value);
    partial void Onid_barangChanged();
    partial void Onid_penggunaChanging(string value);
    partial void Onid_penggunaChanged();
    partial void Onwaktu_peminjamanChanging(string value);
    partial void Onwaktu_peminjamanChanged();
    partial void Onwaktu_pemulanganChanging(string value);
    partial void Onwaktu_pemulanganChanged();
    #endregion
		
		public detailpeminjaman()
		{
			this._barang = default(EntityRef<barang>);
			this._pengguna = default(EntityRef<pengguna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peminjaman", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_peminjaman
		{
			get
			{
				return this._id_peminjaman;
			}
			set
			{
				if ((this._id_peminjaman != value))
				{
					this.Onid_peminjamanChanging(value);
					this.SendPropertyChanging();
					this._id_peminjaman = value;
					this.SendPropertyChanged("id_peminjaman");
					this.Onid_peminjamanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", DbType="VarChar(50)")]
		public string id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					if (this._barang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_barangChanging(value);
					this.SendPropertyChanging();
					this._id_barang = value;
					this.SendPropertyChanged("id_barang");
					this.Onid_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pengguna", DbType="VarChar(50)")]
		public string id_pengguna
		{
			get
			{
				return this._id_pengguna;
			}
			set
			{
				if ((this._id_pengguna != value))
				{
					if (this._pengguna.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_penggunaChanging(value);
					this.SendPropertyChanging();
					this._id_pengguna = value;
					this.SendPropertyChanged("id_pengguna");
					this.Onid_penggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waktu_peminjaman", DbType="VarChar(50)")]
		public string waktu_peminjaman
		{
			get
			{
				return this._waktu_peminjaman;
			}
			set
			{
				if ((this._waktu_peminjaman != value))
				{
					this.Onwaktu_peminjamanChanging(value);
					this.SendPropertyChanging();
					this._waktu_peminjaman = value;
					this.SendPropertyChanged("waktu_peminjaman");
					this.Onwaktu_peminjamanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waktu_pemulangan", DbType="VarChar(50)")]
		public string waktu_pemulangan
		{
			get
			{
				return this._waktu_pemulangan;
			}
			set
			{
				if ((this._waktu_pemulangan != value))
				{
					this.Onwaktu_pemulanganChanging(value);
					this.SendPropertyChanging();
					this._waktu_pemulangan = value;
					this.SendPropertyChanged("waktu_pemulangan");
					this.Onwaktu_pemulanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="barang_detailpeminjaman", Storage="_barang", ThisKey="id_barang", OtherKey="id_barang", IsForeignKey=true)]
		public barang barang
		{
			get
			{
				return this._barang.Entity;
			}
			set
			{
				barang previousValue = this._barang.Entity;
				if (((previousValue != value) 
							|| (this._barang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._barang.Entity = null;
						previousValue.detailpeminjamans.Remove(this);
					}
					this._barang.Entity = value;
					if ((value != null))
					{
						value.detailpeminjamans.Add(this);
						this._id_barang = value.id_barang;
					}
					else
					{
						this._id_barang = default(string);
					}
					this.SendPropertyChanged("barang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_detailpeminjaman", Storage="_pengguna", ThisKey="id_pengguna", OtherKey="id_pengguna", IsForeignKey=true)]
		public pengguna pengguna
		{
			get
			{
				return this._pengguna.Entity;
			}
			set
			{
				pengguna previousValue = this._pengguna.Entity;
				if (((previousValue != value) 
							|| (this._pengguna.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pengguna.Entity = null;
						previousValue.detailpeminjamans.Remove(this);
					}
					this._pengguna.Entity = value;
					if ((value != null))
					{
						value.detailpeminjamans.Add(this);
						this._id_pengguna = value.id_pengguna;
					}
					else
					{
						this._id_pengguna = default(string);
					}
					this.SendPropertyChanged("pengguna");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pengguna")]
	public partial class pengguna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_pengguna;
		
		private string _username;
		
		private string _password;
		
		private string _nama;
		
		private string _status_pengguna;
		
		private string _role;
		
		private EntitySet<detailpeminjaman> _detailpeminjamans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_penggunaChanging(string value);
    partial void Onid_penggunaChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Onstatus_penggunaChanging(string value);
    partial void Onstatus_penggunaChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public pengguna()
		{
			this._detailpeminjamans = new EntitySet<detailpeminjaman>(new Action<detailpeminjaman>(this.attach_detailpeminjamans), new Action<detailpeminjaman>(this.detach_detailpeminjamans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pengguna", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_pengguna
		{
			get
			{
				return this._id_pengguna;
			}
			set
			{
				if ((this._id_pengguna != value))
				{
					this.Onid_penggunaChanging(value);
					this.SendPropertyChanging();
					this._id_pengguna = value;
					this.SendPropertyChanged("id_pengguna");
					this.Onid_penggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(100)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_pengguna", DbType="VarChar(50)")]
		public string status_pengguna
		{
			get
			{
				return this._status_pengguna;
			}
			set
			{
				if ((this._status_pengguna != value))
				{
					this.Onstatus_penggunaChanging(value);
					this.SendPropertyChanging();
					this._status_pengguna = value;
					this.SendPropertyChanged("status_pengguna");
					this.Onstatus_penggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_detailpeminjaman", Storage="_detailpeminjamans", ThisKey="id_pengguna", OtherKey="id_pengguna")]
		public EntitySet<detailpeminjaman> detailpeminjamans
		{
			get
			{
				return this._detailpeminjamans;
			}
			set
			{
				this._detailpeminjamans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailpeminjamans(detailpeminjaman entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = this;
		}
		
		private void detach_detailpeminjamans(detailpeminjaman entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = null;
		}
	}
}
#pragma warning restore 1591
